### PR TITLE
angular markdown editor 

### PR DESCRIPTION
**Pull request by 71ashu**
please make angular markdown editor compatible with bootstrap 4

### CODE REVIEW

**Comment by ghiscoding** [comment]
I'm really not sure what you've done here... you took some of old commits to make a PR?? 
If you want to make a PR that will bring support to BS4, that's fine but don't include the `dist` (build) folder as it's too hard to know what exactly change.

**Comment by 71ashu** [comment]
Ok

**Comment by 71ashu** [comment]
But I would like that the markdown editor compatible with bootstrap 4

**Comment by ghiscoding** [comment]
That is what Open Source Community is for, if you want to help in bringing support to Bootstrap 4 then I certainly welcome PR (Pull Request) for that matter. 

I'm closing this PR since it's obviously **not** a valid PR

**Pull request closed without merging**
