### PR TITLE
Added new attribute to provide factory function for additional buttons

### PR DESCRIPTION
**Pull request by ramarivera**
Added a scope attribute, to be executed in the parent scope in order to provide custom buttons, instead of having to stringify a factory function.

When both additionalButtons and "addExtraButtons" are provided, merge both buttons.

### CODE REVIEW

**Comment by ghiscoding** [comment]
Would it be possible to fix the indentation? It's hard to see what you changed when the PR highlight almost everything has changed :(

**Comment by ramarivera** [comment]
No problem, I'll try to change it

**Comment by ramarivera** [comment]
It seems it didn't work. I'll try again later so its easier to spot changes

**Comment by ghiscoding** [comment]
If you can't get it to work, I can change my original indentation to 2 spaces. I was using Sublime Text in the past and my indentation was not always known, however nowadays I'm with VSCode and follow the standard of 2 spaces. So anyway, I could change the indentation if that helps but you might have to redo the PR. Let me know what is best for you, and yes I asked you to change it because I can't see your code change when everything is red :P

**Comment by ramarivera** [comment]
I think I got it right this time :D

**Comment by ghiscoding** [comment]
Yes I can see the changes now, thanks for that. Would you mind providing an example with your new `buttonFactory` and actually I think it might be best to modify the README at the [editor extra buttons section](https://github.com/ghiscoding/angular-markdown-editor#editor-extra-buttons) with your factory example, that would be great. I assume you tested with and without a factory?

**Comment by ramarivera** [comment]
> I assume you tested with and without a factory?

Unfortunately you assumed wrong :P . I think i fixed it tho.
I'll try to add some examples and an updated readme by the weekend.

**Comment by ghiscoding** [comment]
Will have to close this PR since support of version `1.x` is now over. I'm about to release a new version `2.x` that provide supports for Angular 4+

However, if you still need to use it in `AngularJS`, version `1.1.5` will always be available through [NPM](https://www.npmjs.com/package/angular-markdown-editor/v/1.1.5), thank you

**Pull request closed without merging**
